quarkus.openapi-generator.codegen.input-base-dir=src/main/resources
quarkus.openapi-generator.codegen.spec.openapi.base-package=lichess.api
quarkus.rest-client.lichessExplorer_yaml.url=https://explorer.lichess.ovh